// Anime Characters Database
const animeCharacters = {
    easy: [
        { name: "Naruto", anime: "NARUTO" },
        { name: "Luffy", anime: "ONE PIECE" },
        { name: "Conan", anime: "Case Closed" },
        { name: "Ash", anime: "Pokémon" },
        { name: "Goku", anime: "DRAGON BALL" },
        { name: "Edward Elric", anime: "Fullmetal Alchemist" },
        { name: "Maomao", anime: "The Apothecary Diaries" },
        { name: "Gojo Satoru", anime: "Jujutsu Kaisen" },
        { name: "Inuyasha", anime: "Inu-Yasha" },
        { name: "Negi", anime: "NEGIMA" },
        { name: "All Might", anime: "My Hero Academia" },
        { name: "Sanraku", anime: "Shangri-La Frontier" },
        { name: "Amuro", anime: "Mobile Suit Gundam" },
        { name: "Ken Kaneki", anime: "Tokyo Ghoul" },
        { name: "Levi", anime: "Attack on Titan" },
        { name: "Rudy", anime: "Mushoku Tensei" },
        { name: "Lelouch", anime: "CODE GEASS" },
        { name: "Lupin III", anime: "Lupin III" },
        { name: "Teppei", anime: "B't X" },
        { name: "Gendo Ikari", anime: "Neon Genesis EVANGELION" },
        { name: "Itoshiki Nozomu", anime: "Sayonara, Zetsubou-Sensei" },
        { name: "Elsie", anime: "The World God Only Knows" },
        { name: "Myne", anime: "Ascendance of a Bookworm" },
        { name: "Yona", anime: "Yona of the dawn" },
        { name: "Tanya", anime: "Saga of Tanya the Evil" },
        { name: "Chi", anime: "Chobits" },
        { name: "Rin Tohsaka", anime: "Fate/Stay Night" },
        { name: "Nagisa", anime: "CLANNAD" },
        { name: "Frieren", anime: "Frieren: Beyond Journey's End" },
        { name: "Lynn Minmay", anime: "Macross" }
    ],
    medium: [
        { name: "Tachikoma", anime: "Ghost in the Shell" },
        { name: "RahXephon", anime: "RahXephon" },
        { name: "Patamon", anime: "DIGIMON ADVENTURE" },
        { name: "Eevee", anime: "Pokemon" },
        { name: "Eva-01", anime: "Neon Genesis EVANGELION" },
        { name: "Bonta", anime: "Full Metal Panic!" },
        { name: "Nina Tucker", anime: "Fullmetal Alchemist" },
        { name: "Hige-piyo", anime: "Hige-piyo" },
        { name: "Retsuko", anime: "Aggretsuko" },
        { name: "Legoshi", anime: "BEASTARS" },
        { name: "Odokawa", anime: "Odd Taxi" },
        { name: "Totoro", anime: "My Neighbour Totoro" },
        { name: "Cerberus", anime: "Cardcaptor Sakura" },
        { name: "Koro-Sensei", anime: "Assassination Classroom" },
        { name: "Kon", anime: "Bleach" },
        { name: "Papiyon", anime: "Buso Renkin" },
        { name: "Senku", anime: "Dr.Stone" },
        { name: "Monokuma", anime: "Danganronpa" },
        { name: "Letty", anime: "Dragon Goes House-Hunting" },
        { name: "Lam", anime: "Urusei Yatsura" },
        { name: "Shana", anime: "Shakugan no Shana" },
        { name: "Maria", anime: "Hayate the Combat Butler" },
        { name: "Gutz", anime: "Berserk" },
        { name: "Lagann", anime: "Gurren Lagann" },
        { name: "Black Jack", anime: "Black Jack" },
        { name: "Milfeulle", anime: "Galaxy Angel" },
        { name: "Vash", anime: "Trigun" },
        { name: "Belldandy", anime: "Oh My Goddess!" },
        { name: "Mamoru Takamura", anime: "Hajime No Ippo" },
        { name: "Fate", anime: "Magical Girl Lyrical Nanoha" }
    ],
    hard: [
        { name: "Yukina", anime: "BanG Dream!" },
        { name: "Soma Yukihira", anime: "Food Wars!" },
        { name: "Canal", anime: "LOST UNIVERSE" },
        { name: "Hinata", anime: "Haikyu" },
        { name: "Shin", anime: "Kingdom" },
        { name: "Rimuru", anime: "That Time I Got Reincarnated as a Slime" },
        { name: "Shiro", anime: "No Game No Life" },
        { name: "Kuga Yuma", anime: "World Trigger" },
        { name: "Dazai", anime: "Bungo Stray Dogs" },
        { name: "Chisato", anime: "Lycoris Recoil" },
        { name: "Shin-chan", anime: "Crayon Shin-chan" },
        { name: "Goro", anime: "Major" },
        { name: "Gash", anime: "Zatch Bell!" },
        { name: "Kitaro", anime: "GeGeGe no Kitaro" },
        { name: "Yusuke Urameshi", anime: "Yu Yu Hakusho" },
        { name: "Hitomi Kanzaki", anime: "The Vision of Escaflowne" },
        { name: "Yoichi Isagi", anime: "Blue Lock" },
        { name: "Denji", anime: "Chainsaw Man" },
        { name: "Asuna Yuuki", anime: "Sword Art Online" },
        { name: "Ai Hoshino", anime: "Oshi no Ko" },
        { name: "Spike Spiegel", anime: "Cowboy Bebop" },
        { name: "Kafka Hibino", anime: "Kaiju No. 8" },
        { name: "Riko", anime: "Made in Abyss" },
        { name: "Roxy", anime: "Mushoku Tensei" },
        { name: "Emma", anime: "The Promised Neverland" },
        { name: "Lloyd", anime: "The Greatest Demon Lord Is Reborn" },
        { name: "Momo Ayase", anime: "Dandadan" },
        { name: "Hitori Goto", anime: "Bocchi the Rock!" },
        { name: "Revy", anime: "Black Lagoon" },
        { name: "Sakura Momoko", anime: "Chibi Maruko-chan" }
    ]
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = animeCharacters;
}
